name: estetikvitrini
description: Estetik Vitrini

publish_to: 'Hicret'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  carousel_nullsafety: ^0.1.1
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_html: ^2.1.2
  flutter_math_fork: ^0.5.0
  flutter_progress_hud: ^2.0.0
  flutter_svg: ^0.23.0+1
  flutter_svg_provider: ^0.1.9
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  http: ^0.13.3
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  line_icons: ^2.0.1
  mask_text_input_formatter: ^2.0.0
  provider: ^6.0.0
  pull_to_refresh: ^2.0.0
  searchable_dropdown: ^1.1.3
  shared_preferences: ^2.0.6
  story_view: ^0.13.1
  table_calendar: ^3.0.2
  url_launcher: ^6.0.10
  webview_flutter: ^2.0.12
  zoomable_image: ^1.3.1
  rich_editor: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: futura_medium_bt
      fonts:
        - asset: assets/fonts/futura_medium_bt.ttf

    - family: nouvelle_vague_final
      fonts:
        - asset: assets/fonts/nouvelle_vague_final.ttf

    - family: gothic_book
      fonts:
        - asset: assets/fonts/gothic_book.ttf

    - family: futura_light_bt
      fonts:
        - asset: assets/fonts/futura_light_bt.ttf
