name: estetikvitrini
description: Estetik Vitrini

publish_to: 'Hicret'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_pro: null
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  flutter_facebook_auth: ^3.5.0
  flutter_progress_hud: ^2.0.0
  flutter_svg: null
  flutter_svg_provider: ^0.1.9
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.0.7
  intl: null
  line_icons: null
  provider: null
  story_view: ^0.13.1
  table_calendar: null
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: futura_medium_bt
      fonts:
        - asset: assets/fonts/futura_medium_bt.ttf

    - family: nouvelle_vague_final
      fonts:
        - asset: assets/fonts/nouvelle_vague_final.ttf
