name: estetikvitrini
description: Estetik Vitrini

publish_to: 'Hicret'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_pro: ^1.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_progress_hud: ^2.0.0
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.9
  font_awesome_flutter: ^9.1.0
  http: ^0.13.3
  intl: ^0.17.0
  line_icons: ^2.0.1
  provider: ^5.0.0
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  story_view: ^0.13.1
  table_calendar: ^3.0.2
  toast: ^0.1.5
  webview_flutter: ^2.0.12
  dropdown_search: ^0.4.9
  searchable_dropdown: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: futura_medium_bt
      fonts:
        - asset: assets/fonts/futura_medium_bt.ttf

    - family: nouvelle_vague_final
      fonts:
        - asset: assets/fonts/nouvelle_vague_final.ttf

    - family: gothic_book
      fonts:
        - asset: assets/fonts/gothic_book.ttf
